- src/blocks/common/popup-hint/popup-hint.css
https://jira.railsc.ru/browse/PC4-23759
> fix(pulscen): popup-hint fix

- src/blocks/pulscen/fonts/fonts.css
[MAJOR] присвоит шрифт Open Sans к body и уберет присвоение ко всем (*)
элементам
https://jira.railsc.ru/browse/PC4-23860
> fix(pulscen): fonts fix

- package.json
- src/colors/blizko.json
[PATCH] Добавим цвет amber для близки
> fix: добавим недостающий цвет

- src/blocks/common/button/button_green.css
- src/blocks/common/button/example/green.html
- src/blocks/common/button/index.js
- src/blocks/common/form/form.css
- src/blocks/common/popup-hint/popup-hint.css
- src/blocks/common/popup-hint/popup-hint_with-icon.css
- src/blocks/pulscen/button/button_green.css
- src/blocks/pulscen/button/example/green.html
- src/blocks/pulscen/button/index.js
- src/blocks/pulscen/form/form.css
[MAJOR]: добавлен модификатор aui-button_green, убран z-index у
popup-hint, изменены отступы у form
https://jira.railsc.ru/browse/PC4-23753
> feature(pulscen): добавлен модификатор aui-button_green, изменены popup-hint, form

- src/blocks/pulscen/button/button_cart.css
- src/blocks/pulscen/button/button_only-icon.css
- src/blocks/pulscen/button/example/only-icon.html
- src/blocks/pulscen/button/index.js
[MAJOR]: button_cart содержит текст и иконку, добавлен модификатор
button_only-icon для кнопки с иконкой без текста
https://jira.railsc.ru/browse/PC4-23872
> feature(pulscen): изменение button_cart, добавление button_only-icon

- src/blocks/common/enhanced-checkbox/checkbox.css
- src/blocks/common/enhanced-checkbox/example/common.html
- src/blocks/common/enhanced-checkbox/index.js
> Add common enhanced checkbox

- src/blocks/pulscen/button/index.js
[PATCH]: поправлен порядок подключения файлов у button
https://jira.railsc.ru/browse/PC4-23872
> fix(pulscen): поправлен порядок подключения button

- src/blocks/pulscen/button/button_cart.css
[PATCH]: убираем адативность у кнопки корзины
https://jira.railsc.ru/browse/PC4-23875
> feature(pulscen): изменение button_cart

- src/blocks/pulscen/button/button_cart.css
[PATCH]: добавление адаптива кнопке button_cart
https://jira.railsc.ru/browse/PC4-23875
> fix(pulscen): правка кнопки корзины

- src/blocks/pulscen/button/button.css
[MINOR]: добавит модификатор button_disabled
https://jira.railsc.ru/browse/PC4-23753
> feature(pulscen): добавлен модификатор button_disabled

- src/blocks/common/spinner/spinner.css
[PATCH] Спиннер в мобильной версии выглядил не верно из-за того что на пц в мобиле не подключен jquery-ui-1.8.4.custom.scss. Теперь вид спиннера не зависит от этих стилей.
https://jira.railsc.ru/browse/ORDERS-2524
> fix: поправим вид спиннера

- src/blocks/pulscen/button/button_only-icon.css
- src/blocks/pulscen/button/button_small.css
[PATCH]: правки button
https://jira.railsc.ru/browse/PC4-23902
> feature(pulscen): правки button

- src/blocks/blizko/fonts/example/common.html
[MINOR] Добавим характеристики шрифтов для более удобного поиска
> feature: добавим характеристики шрифтов

- src/blocks/blizko/button/button_group.css
- src/blocks/blizko/button/example/example_buttons.html
- src/blocks/blizko/button/index.js
[MINOR] Добавлены кнопки для создания групп кнопок
https://jira.railsc.ru/browse/BPC-14961
> feature(blizko): add button groups

- src/blocks/pulscen/button/button_chat.css
[MINOR]: изменение button_chat
https://jira.railsc.ru/browse/PC4-24038
> feature(pulscen): изменение button_chat

- src/blocks/pulscen/button/button.css
[PATCH]: уберет определение цвета с aui-button_disabled
https://jira.railsc.ru/browse/PC4-24120
> fix(pulscen): remove color-rule from aui-button_disabled

- src/blocks/common/app-button/app-button_dark.css
- src/blocks/common/app-button/example/common.html
- src/blocks/common/app-button/index.js
- src/blocks/pulscen/app-button/app-button_dark.css
- src/blocks/pulscen/app-button/example/common.html
- src/blocks/pulscen/app-button/index.js
[MINOR]: добавлен модификатор aui-app-button_dark
https://jira.railsc.ru/browse/PC4-24129
> feature(pulscen): добавление модификатора для app-button

- src/blocks/blizko/radio/example/common.html
- src/blocks/blizko/radio/index.js
- src/blocks/blizko/radio/radio_color.css
[MINOR] Добавим модификатор цвета для input radio
https://jira.railsc.ru/browse/BPC-15371
> feature: добавим цвет для radio

- src/blocks/common/message/message.css
- src/blocks/pulscen/rubricator/rubricator.css
[PATCH] правки rubricator
https://jira.railsc.ru/browse/PC4-23923
> fix(pulscen): rubricator fixes

- src/blocks/pulscen/breadcrumbs/breadcrumbs_with-rubrics.css
[PATCH]: увеличен z-index у элемента breadcrumbs
https://jira.railsc.ru/browse/PC4-24176
> fix(pulscen): правка breadcrumbs

- src/blocks/pulscen/rubricator/example/common.html
- src/blocks/pulscen/rubricator/rubricator.css
[PATCH]: правки вложенности рубрик в рубрикаторе
https://jira.railsc.ru/browse/PC4-23923
> fix(pulscen): доработки рубрикатора

- src/blocks/pulscen/rubricator/rubricator.css
[PATCH]: правка стрелки рубрикатора
https://jira.railsc.ru/browse/PC4-23923
> fix(pulscen): правка рубрикатора

- src/blocks/pulscen/button/button_only-icon.css
[PATCH]: прячем текст у aui-button_only-icon
https://jira.railsc.ru/browse/PC4-24053
> fix(pulscen): доработка модификатора aui-button_only-icon

- src/colors/pulscen.json
[MINOR]: добавлен цвет default-very-light-gray
https://jira.railsc.ru/browse/PC4-24317
> feature(pulscen): добавлен цвет default-very-light-gray

- package-lock.json
- src/blocks/pulscen/button/button_chat.css
[PATCH]: добавлено перекрытие стилей кнопки aui-button_chat для ссылок :visited
https://jira.railsc.ru/browse/PC4-24177
> fix(pulscen): правка кнопки aui-button_chat

- src/blocks/pulscen/button/button.css
- src/blocks/pulscen/fonts/fonts.css
[MINOR]: уберет отработку событий на заблокированных кнопках;
добавит font-display к шрифту openSans
https://jira.railsc.ru/browse/PC4-24323
> feature(pulscen): reject event for disabled button, add font-display

- src/blocks/pulscen/link/example/gray.html
- src/blocks/pulscen/link/index.js
- src/blocks/pulscen/link/link.css
- src/blocks/pulscen/link/link_callback.css
- src/blocks/pulscen/link/link_gray.css
- src/blocks/pulscen/link/link_phone.css
[MINOR]: добавлен модификатор link_gray
https://jira.railsc.ru/browse/PC4-24618
> feature(pulscen): добавлен модификатор link_gray

- src/blocks/common/button/button.css
- src/blocks/pulscen/button/button.css
- src/blocks/pulscen/button/button_callback.css
- src/blocks/pulscen/button/button_cart-with-item.css
- src/blocks/pulscen/button/button_cart.css
- src/blocks/pulscen/button/button_chat.css
- src/blocks/pulscen/button/button_green.css
- src/blocks/pulscen/button/button_transparent-grey.css
- src/blocks/pulscen/button/button_transparent-yellow.css
- src/blocks/pulscen/button/button_transparent.css
https://jira.railsc.ru/browse/PC4-24806
> feature(pulscen button): disallow hover for touch device

- src/blocks/pulscen/indents/example/common.html
- src/blocks/pulscen/indents/indents.css
[MINOR]: добавлено новое значение indent
https://jira.railsc.ru/browse/PC4-24763
> feature(pulscen): add new indent value

- src/blocks/common/message/example/common.html
- src/blocks/common/message/index.js
- src/blocks/common/message/message_italic.css
- src/blocks/common/message/message_small.css
[MINOR]: добавление модификаторов для message
https://jira.railsc.ru/browse/PC4-24946
> feature: добавление модификаторов для message

- src/blocks/common/toggler/toggler.js
https://jira.railsc.ru/browse/PC4-25149
> fix(toggler): правка тогглера для элементов с индексом

- src/blocks/common/toggler/toggler.js
[PATCH]: правки toggler
https://jira.railsc.ru/browse/PC4-25149
> fix: правки toggler

- src/blocks/pulscen/button/button_callback.css
https://jira.railsc.ru/browse/PC4-24870
[PATCH]: Добавит стили для псевдо-элемента кнопки при ховер эффекте для мобильных девайсов
> fix(button callback): fix button styles on mobiles

- src/blocks/pulscen/button/button_gray.css
- src/blocks/pulscen/button/example/gray.html
- src/blocks/pulscen/button/index.js
https://jira.railsc.ru/browse/PC4-25480
> feature(pulscen): add gray button

- src/blocks/pulscen/button/button_big.css
- src/blocks/pulscen/button/button_cart.css
https://jira.railsc.ru/browse/PC4-25510
> feature(button cart): add styles for aui-button_cart:link

- src/blocks/blizko/form/example/common.html
- src/blocks/blizko/form/form.css
- src/blocks/blizko/form/index.js
https://jira.railsc.ru/browse/BPC-17064
> feature(blizko form): add blizko styles

- src/blocks/pulscen/button/button_gray.css
[PATCH]: добавит стили для button_gray ссылки
https://jira.railsc.ru/browse/PC4-25480
> fix(pulscen): add style for button_gray link

- src/colors/pulscen.json
https://jira.railsc.ru/browse/PC4-25732
> feature(pulscen): add new colors

- src/colors/pulscen.json
https://jira.railsc.ru/browse/PC4-25732
> fix(pulscen): change new color prefix

- src/blocks/pulscen/button/button_gray.css
https://jira.railsc.ru/browse/PC4-25480
> fix(pulscen): add style for hover button_gray link

- src/blocks/common/modules-loader/modules-loader.js
[PATCH]: добавит модулям свойство initiated
https://jira.railsc.ru/browse/PC4-25630
> fix(module_loader): add prop initiated to modules

- src/blocks/common/z-index/example/common.html
- src/blocks/common/z-index/index.js
- src/blocks/common/z-index/z-index.css
https://jira.railsc.ru/browse/PC4-26561
> feature: add z-index

- src/blocks/pulscen/checkbox/checkbox_default.css
- src/blocks/pulscen/checkbox/checkbox_default.svg
- src/blocks/pulscen/checkbox/example/default.html
- src/blocks/pulscen/checkbox/index.js
https://jira.railsc.ru/browse/PC4-26561
> feature(pulscen): add default checkbox

- src/colors/lookmart.json
[MINOR] Добавит цвета из макета по редизайну портала
https://jira.railsc.ru/browse/SG-7074
> feature(colors): add new custom colors

- src/blocks/common/istorage/istorage.js
[PATCH]: подтянет изменения istorage из apress_aplication
https://jira.railsc.ru/browse/PC4-26969
> fix(istorage): update file from apress_aplication

- package-lock.json
- src/blocks/pulscen/button-link/button-link_dim-red-nohover.css
- src/blocks/pulscen/button-link/button-link_underline.css
- src/blocks/pulscen/button-link/example/dim_red_nohover.html
- src/blocks/pulscen/button-link/example/underline.html
- src/blocks/pulscen/button-link/index.js
https://jira.railsc.ru/browse/PC4-26734
> feature(button-link ПЦ): добавит два стиля для псевдоссылок [skip ci]

- src/blocks/common/deferred-resources-loader/index.js
[PATCH] заменит Object.values на for in
https://jira.railsc.ru/browse/BPC-18918
> fix: change Object.values on for in

- package-lock.json
- src/blocks/lookmart/social-networks/social-networks.css
- src/blocks/lookmart/social-networks/social-networks_old.css
[MINOR] исправит выравнивание блоков соц.сетей
https://jira.railsc.ru/browse/SG-7149
> fix(lookmart): fix social-networks block alignment

- src/blocks/pulscen/button/button_thin.css
https://jira.railsc.ru/browse/PC4-26981
> fix(pulscen): add button_thin rules for link

- src/blocks/pulscen/link/link_phone.css
https://jira.railsc.ru/browse/PC4-26994
> feature(pulscen): повернет значёк ссылки телефона на 90 градусов

- src/blocks/blizko/button-link/button-link.css
- src/blocks/blizko/button-link/button-link_dashed.css
- src/blocks/blizko/button-link/example/common.html
- src/blocks/blizko/button-link/index.js
- src/blocks/blizko/input/example/example_input.html
- src/blocks/blizko/input/index.js
- src/blocks/blizko/input/input_textarea.css
- src/blocks/blizko/select/select.css
fix(select.css): add pointer-events none to select icon
https://jira.railsc.ru/browse/BPC-19032
> add input_textarea, button-link_dashed and fixed select icon

- src/blocks/pulscen/link/example/bolder.html
- src/blocks/pulscen/link/example/dark.html
- src/blocks/pulscen/link/example/dotted.html
- src/blocks/pulscen/link/index.js
- src/blocks/pulscen/link/link_bolder.css
- src/blocks/pulscen/link/link_dark.css
- src/blocks/pulscen/link/link_dotted.css
https://jira.railsc.ru/browse/PC4-26994
> feature(pulscen): add new styles for link

- src/blocks/blizko/base-block/base-block_adaptive.css
- src/blocks/blizko/base-block/example/base_block.html
- src/blocks/blizko/base-block/index.js
- src/blocks/blizko/tooltip/example/tooltip.html
- src/blocks/blizko/tooltip/tooltip.css
https://jira.railsc.ru/browse/BPC-18980
> fix: remade tooltip logic & separate base-block from modifiers

- package-lock.json
- src/blocks/common/spinner/spinner.css
https://jira.railsc.ru/browse/PC4-26991
> fix(Spinner type="number"): уберет стрелочки

- src/blocks/blizko/button-link/button-link_black-l65.css
- src/blocks/blizko/button-link/example/common.html
- src/blocks/blizko/button-link/index.js
- src/blocks/blizko/radio/index.js
- src/blocks/blizko/radio/radio.css
- src/blocks/blizko/radio/radio_small.css
[MINOR]: Добавит модификатор radio_small, модификатор button-link_black-l65 и центровку радиобаттона когда текст в лейбле превышает 1 строку
https://jira.railsc.ru/browse/BPC-18982
> feat: add blizko radio_small, radio centering, button-link_black-l65

- src/blocks/blizko/close-button/close-button.css
- src/blocks/blizko/close-button/example/example_buttons.html
- src/blocks/blizko/close-button/index.js
[MINOR]: Добавит закрывающий крестик для Близки
https://jira.railsc.ru/browse/BPC-18982
> feat: add blizko close-button

- src/blocks/common/admin-enhanced-checkbox/admin-enhanced-checkbox.css
[MINOR] Поправим стили
https://jira.railsc.ru/browse/BPC-19059
> fix: fix admin checkbox toggler

- src/blocks/pulscen/button/button_big-text.css
- src/blocks/pulscen/button/button_callback.css
- src/blocks/pulscen/button/example/big_text.html
- src/blocks/pulscen/button/index.js
- src/blocks/pulscen/cs-button/button_company-site.css
- src/blocks/pulscen/cs-button/button_square.css
- src/blocks/pulscen/cs-button/example/company_site.html
- src/blocks/pulscen/cs-button/example/square.html
- src/blocks/pulscen/cs-button/index.js
https://jira.railsc.ru/browse/PC4-27111
> feature(pulscen): добавит новый раздел кнопок и кнопок для СК

- src/blocks/blizko/button-link/button-link.css
- src/blocks/blizko/button-link/button-link_dashed.css
- src/blocks/blizko/button-link/button-link_orange.css
- src/blocks/blizko/button-link/example/common.html
- src/blocks/blizko/button-link/index.js
[MINOR]: Обнулит нативный паддинг у кнопки и добавит модификатор для оранжевого цвета
https://jira.railsc.ru/browse/BPC-19106
> fix: remove native button padding and add button-link_orange

- src/blocks/blizko/button-link/button-link.css
- src/blocks/blizko/button-link/button-link_dashed.css
- src/blocks/blizko/button-link/example/common.html
- src/blocks/blizko/input/example/example_input.html
- src/blocks/blizko/input/input.css
fix: correct input background
[MINOR]: Добавит стили отображения залоченной кнопки и исправит фон у инпута
https://jira.railsc.ru/browse/BPC-19036
> feat: add button-link disabled styles

- src/blocks/blizko/input/input.css
- src/blocks/blizko/input/input_textarea.css
[MINOR]: Добавит оранжевую звездочку у обязательного input и input_textarea и исправит цвет границы поля в заполненном и пустом состоянии
https://jira.railsc.ru/browse/BPC-18935
> fix: fixed input & input_textarea for blizko

- src/blocks/common/selectric/selectric.css
https://jira.railsc.ru/browse/PC4-26911
> fix(selectric): add z-index

- src/blocks/pulscen/cs-button-link/cs-button-link_add.css
- src/blocks/pulscen/cs-button-link/cs-button-link_add.svg
- src/blocks/pulscen/cs-button-link/example/add.html
- src/blocks/pulscen/cs-button-link/index.js
https://jira.railsc.ru/browse/PC4-27164
> feature(Pulscen): add aui-cs-button-link_add

- src/blocks/common/button/button_green.css
- src/blocks/pulscen/button/button_green.css
- src/blocks/pulscen/button/index.js
https://jira.railsc.ru/browse/PC4-27165
> fix(Pulscen): исправит стили aui-button_green применяемые к ссылке

- src/blocks/pulscen/button/button_transparent-red.css
- src/blocks/pulscen/button/button_transparent-yellow.css
- src/blocks/pulscen/button/example/transparent_red.html
- src/blocks/pulscen/button/index.js
Так же пофиксит поведение стилей желтой кнопки на ссылке.
https://jira.railsc.ru/browse/PC4-27210
> feature(Pulscen): добавит aui-button_transparent-red

- src/blocks/blizko/button-link/button-link.css
[PATCH]: Добавит наследовние шрифта в button-link.css.
https://jira.railsc.ru/browse/BPC-19106?focusedCommentId=200566&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-200566
> fix: add Blizko button-link.css font:inherit

- src/blocks/common/button/button_transparent.css
https://jira.railsc.ru/browse/PC4-27215
> fix(common\aui-button_transparent): исправит залипание ховера на сенсорных экранах

- src/blocks/common/admin-related-products/admin-related-products.css
- src/blocks/common/admin-related-products/example/common.html
https://jira.railsc.ru/browse/GOODS-2924
> fix: text to link in related products

- src/blocks/common/polyfills/polyfills.js
https://jira.railsc.ru/browse/BPC-19369
https://jira.railsc.ru/browse/BPC-19389
> fix: add Object.values, Object.entries polyfills, remove promise polyfill

- src/blocks/common/admin-link/admin-link.css
- src/blocks/common/admin-rubric-select/admin-rubric-select.css
- src/blocks/common/admin-rubric-select/example/common.html
- src/blocks/common/admin-search/admin-search.css
- src/blocks/common/admin-search/example/common.html
https://jira.railsc.ru/browse/GOODS-2866
> fix: rubricator components design fixes

- src/blocks/common/admin-tabber/admin-tabber.css
- src/colors/common.json
https://jira.railsc.ru/browse/PC4-27066
> feature(admin): add color, change tabber style

- package-lock.json
- src/blocks/blizko/button/button_color.css
- src/blocks/blizko/button/button_round.css
- src/blocks/blizko/button/example/example_buttons.html
- src/blocks/blizko/button/index.js
https://jira.railsc.ru/browse/BPC-19372
> feature: add blizko button without round

- src/blocks/blizko/link/link.css
https://jira.railsc.ru/browse/BPC-19312
> fix: add cursor pointer blizko link

- src/blocks/common/admin-number-input/admin-number-input.css
- src/blocks/common/admin-text-input/admin-text-input.css
- src/blocks/common/admin-text-input/example/common.html
https://jira.railsc.ru/browse/GOODS-2960
> fix: text and number inputs fixes

- src/blocks/common/admin-battery-popup/admin-battery-popup.css
- src/blocks/common/admin-battery/admin-battery.css
- src/blocks/common/admin-checkbox/admin-checkbox.css
- src/blocks/common/admin-checkbox/example/common.html
- src/blocks/common/admin-checkbox/index.js
- src/blocks/common/admin-textarea/admin-textarea.css
- src/colors/common.json
https://jira.railsc.ru/browse/GOODS-2866
https://jira.railsc.ru/browse/GOODS-2892
> feat: add checkbox component and battery mobile styles

- src/blocks/common/admin-number-input/admin-number-input.css
- src/blocks/common/admin-number-input/example/common.html
- src/blocks/common/admin-text-input/admin-text-input.css
- src/blocks/common/admin-text-input/example/common.html
https://jira.railsc.ru/browse/GOODS-2960
> fix: style admin text and number input counters

- src/blocks/common/admin-colorpicker/admin-colorpicker.css
- src/blocks/common/admin-colorpicker/example/common.html
- src/blocks/common/admin-colorpicker/index.js
- src/blocks/common/admin-range-input/admin-range-input.css
- src/blocks/common/admin-range-input/example/common.html
- src/blocks/common/admin-range-input/index.js
https://jira.railsc.ru/browse/PC4-27121
> feature(common): add admin-colorpicker & admin-range-input

- src/blocks/common/admin-button/admin-button.css
https://jira.railsc.ru/browse/PC4-27075
> fix(admin button): add styles for link & visited

- package-lock.json
- src/blocks/pulscen/button/button_callback-big.css
- src/blocks/pulscen/button/example/callback_big.html
- src/blocks/pulscen/button/index.js
- src/blocks/pulscen/link/example/bolder.html
- src/blocks/pulscen/link/index.js
- src/blocks/pulscen/link/link_bolder.css
Что немного увеличит размер иконки телефона
https://jira.railsc.ru/browse/PC4-27599
> feature(PC): добавит класс aui-button_callback-big

- src/blocks/common/admin-checkbox/admin-checkbox.css
- src/blocks/common/admin-checkbox/example/common.html
- src/blocks/pulscen/link/example/disabled.html
- src/blocks/pulscen/link/index.js
- src/blocks/pulscen/link/link_disabled.css
[MINOR]: добавит модификатор к checkbox label, стили к disabled link
исправит опечатку
> feature: add checkbox labels modificators, disabled link, fix misprint

- package-lock.json
- src/blocks/lookmart/fonts/example/small_size.html
- src/blocks/lookmart/fonts/fonts.css
[MINOR] Добавит новую переменную с размером шрифта
https://jira.railsc.ru/browse/SG-7423
> feature(fonts): create new variable for fonts

- src/blocks/pulscen/link/link_disabled.css
[PATCH]: добавит стили для link_disabled
https://jira.railsc.ru/browse/PC4-27403
> fix(pulscen): add visited style for link_disabled

- package-lock.json
- src/blocks/blizko/input/example/example_input.html
- src/blocks/blizko/input/input.css
[MINOR]: добавит статический модификатор для input и label
https://jira.railsc.ru/browse/BPC-19576
> feature: add input and label modifiers

- src/blocks/blizko/button/button.css
- src/blocks/blizko/button/example/example_buttons.html
[MINOR]: Добавит модификатор кнопки с тонкой рамкой
https://jira.railsc.ru/browse/BPC-19827
> feature: add a thin border button

- src/colors/common.json
[MINOR]: добавит цвета для новой статистики компании
https://jira.railsc.ru/browse/BPC-19477
> feature: add colors for company statistics

- src/colors/lookmart.json
[MINOR] Добавит новую переменную с тёмно-серым цветом
https://jira.railsc.ru/browse/SG-7312
> feat(colors): add variable for new gray-color

- src/colors/common.json
[MINOR]: добавит недостающие цвета в админку
https://jira.railsc.ru/browse/BPC-19926
> feature: add colors for admin panel

- package-lock.json
- src/blocks/pulscen/cs-button/button_company-site-big.css
https://jira.railsc.ru/browse/PC4-27741
> feature(ПЦ): применит стили button_company-site-big к ссылкам

- src/blocks/common/admin-toolbar-button/admin-toolbar-button.css
- src/blocks/common/admin-toolbar-button/admin-toolbar-button_small.css
- src/blocks/common/admin-toolbar-button/example/small.html
- src/blocks/common/admin-toolbar-button/index.js
[MINOR]: добавит модификатор small блоку admin-toolbar-button
https://jira.railsc.ru/browse/PC4-27855
> feature(admin-toolbar-button): добавит модификатор small

- src/blocks/common/admin-hint/admin-hint.css
- src/blocks/common/admin-rubric-select/admin-rubric-select.css
- src/blocks/common/admin-textarea/admin-textarea.css
[PATCH]: изменит стили для элементов админки hints, rubricator, textarea
https://jira.railsc.ru/browse/PC4-27881
> fix(admin): change styles for hints, rubricator, textarea

- src/blocks/blizko/button-link/button-link.css
- src/blocks/blizko/button-link/button-link_opacity_light.css
- src/blocks/blizko/button-link/example/common.html
- src/blocks/blizko/button-link/index.js
- src/blocks/blizko/link/example/common.html
- src/blocks/blizko/link/index.js
- src/blocks/blizko/link/link_opacity_light.css
[MINOR]: добавит новый компонент ссылки
https://jira.railsc.ru/browse/BPC-20243
> feat(desktop): add aui-link_transparent element

- src/blocks/common/admin-textarea/admin-textarea.css
- src/blocks/common/admin-upload-field/admin-upload-field.css
[PATCH]: добавит максимальную ширину для upload-field, и
бордер на фокус для textarea
> fix(admin): add upload-field max-width, textarea focus border

- src/blocks/blizko/button-link/button-link.css
- src/blocks/blizko/link/link.css
[PATCH]: удалит подчеркивание после нажатия
https://jira.railsc.ru/browse/BPC-20306
> fix(blizko mobile): remove underline after clicking

- src/blocks/pulscen/button/example/demo_callback.html
- src/blocks/pulscen/button/example/demo_cart.html
- src/blocks/pulscen/button/example/demo_common.html
[MINOR]: добавит демо страницы для кнопок пц
https://jira.railsc.ru/browse/PC4-28148
> feature(pulscen): add demo pages for buttons

- src/blocks/blizko/favorite-button/favorite-button.css
[PATCH]: исправит cursor pointer при наведении на кнопку добавить в избранное
> fix(blizko): fix cursor pointer on favorite button

- src/blocks/pulscen/text-label/example/clickable.html
- src/blocks/pulscen/text-label/example/larger.html
- src/blocks/pulscen/text-label/index.js
- src/blocks/pulscen/text-label/text-label.css
- src/blocks/pulscen/text-label/text-label_clickable.css
- src/blocks/pulscen/text-label/text-label_highlighted.css
- src/blocks/pulscen/text-label/text-label_larger.css
[MINOR] изменит text-label_highlighted, добавит text-label_larger и text-label_clickable
https://jira.railsc.ru/browse/PC4-28122
> feature(PC): изменит лейбу highlighted и добавит класс для кликабельных лейб

- src/blocks/pulscen/breadcrumbs/breadcrumbs.css
- src/blocks/pulscen/rubricator/rubricator.css
[PATCH]: изменит стили рубрикатора и крошек ПЦ
https://jira.railsc.ru/browse/PC4-28118
> fix(pulscen): change breadcrumbs & rubricator styles

- src/blocks/blizko/marketing-label/example/marketing_label_example.html
- src/blocks/blizko/marketing-label/index.js
- src/blocks/blizko/marketing-label/marketing-label.css
- src/blocks/blizko/marketing-label/marketing-label_desktop.css
- src/blocks/blizko/marketing-label/marketing-label_mobile.css
[MINOR]: добавит маркетинговые метки товаров на Blizko
https://jira.railsc.ru/browse/BPC-20581
> feat(blizko): add product marketing tags

- src/blocks/blizko/button/button_color.css
- src/blocks/blizko/button/button_size.css
- src/blocks/blizko/button/example/example_buttons.html
[MINOR]: добавит новые стили для кнопок на Blizko
https://jira.railsc.ru/browse/BPC-20569
> feat(blizko): add new styles for buttons

- src/blocks/pulscen/breadcrumbs/breadcrumbs_with-rubrics.css
- src/blocks/pulscen/rubricator/rubricator.css
[PATCH]: удалит радиус у иконки хлебных крошек, добавит отступ рубрикатору
https://jira.railsc.ru/browse/PC4-28118
> fix(pulscen): remove breadcrumbs icon radius, add margin to rubricator

- src/blocks/pulscen/button/button_responsive.css
- src/blocks/pulscen/button/example/common_responsive.html
- src/blocks/pulscen/button/index.js
[MINOR]: добавит aui-button_responsive
https://jira.railsc.ru/browse/PC4-28162
> feature(PC): добавит aui-button_responsive

- src/blocks/blizko/input/input.css
[PATCH]: исправит ошибку с перекрытием контура инпута лейблом при автокомплите
https://jira.railsc.ru/browse/BPC-20504
> fix(blizko): fix background label input

- src/blocks/pulscen/button/button_cart-with-item-no-border.css
- src/blocks/pulscen/button/button_cart-without-border.css
[PATCH]: поправит отступы кнопок корзины
https://jira.railsc.ru/browse/PC4-28228
> fix(PC): поправит отступы кнопок корзины

- src/colors/lookmart.json
[MINOR] добавит новый цвет в библиотеку компонентов
https://jira.railsc.ru/browse/SG-7549
> feat(lookmart): adds a new color

- src/blocks/blizko/marketing-label/marketing-label_desktop.css
- src/blocks/blizko/marketing-label/marketing-label_mobile.css
[PATCH]: удалит ограничение ширины меток
https://jira.railsc.ru/browse/BPC-20581
> fix(blizko): fix label width

- src/blocks/pulscen/rubricator/rubricator.css
[PATCH]: change the link cursor
https://jira.railsc.ru/browse/PC4-28295
> fix(Pulscen): change the link cursor

- src/blocks/blizko/favorite-button/example/mobile.html
- src/blocks/blizko/favorite-button/favorite-button.css
- src/blocks/blizko/favorite-button/favorite-button_mobile.css
- src/blocks/blizko/favorite-button/index.js
[MINOR]: добавит кнопку избранных товаров для мобилы
https://jira.railsc.ru/browse/BPC-20389
> feature(blizko): add mobile favorite button

- src/blocks/blizko/marketing-label/example/marketing_label_example.html
- src/blocks/blizko/marketing-label/index.js
- src/blocks/blizko/marketing-label/marketing-label.css
- src/blocks/blizko/marketing-label/marketing-label_rating.css
[MINOR]: добавит стили рейтинговых меток
https://jira.railsc.ru/browse/BPC-20709
> feat(blizko): add rating labels

- package-lock.json
- src/blocks/pulscen/button/button_visit.css
- src/blocks/pulscen/button/button_visit.svg
- src/blocks/pulscen/button/example/visit.html
- src/blocks/pulscen/button/index.js
[MINOR] Добавил кнопку button_visit для вывода групп списком на новых страницах.
https://jira.railsc.ru/browse/GOODS-3174
> feature: add button_visit

- src/blocks/blizko/favorite-button/favorite-button_cart.css
[PATCH]: исправит стили для кнопки добавления в избранные товары в
safari
https://jira.railsc.ru/browse/BPC-20750
> fix(blizko): fix favorite button for safari

- package-lock.json
- src/blocks/pulscen/button/button_cart-without-border.css
[PATCH]: уберет отступ справа для кнопки добавления в корзину
https://jira.railsc.ru/browse/PC4-28409
> fix(pulscen) remove padding right on aui-button_cart-without-border

- src/blocks/pulscen/rubricator/rubricator.css
[MINOR]: уменьшит ширину скролбара, добавит модификатор _stretched-overflow
https://jira.railsc.ru/browse/PC4-28399
> feature(Pulscen Rubricator): уменьшит ширину скролбара, добавит модификатор _stretched-overflow

- src/blocks/common/button/button_visit-no-border.css
- src/blocks/common/button/button_visit.css
[PATCH] Убрал переменные с кнопок visit и visit-no-border из общего каталога.
https://jira.railsc.ru/browse/GOODS-3174
> fix: уберет переменные с кнопок visit и visit-no-border

- src/blocks/common/button/button_transparent.css
[MINOR]: Изменит толщину задизайбленой кнопки
https://jira.railsc.ru/browse/BPC-20893
> feature(blizko): change width border for disabled aui-button

- src/blocks/pulscen/button/button_small.css
- src/blocks/pulscen/link/example/medium_dark.html
- src/blocks/pulscen/link/index.js
- src/blocks/pulscen/link/link_medium_dark.css
[MINOR]: change aui-button_small styles, add aui-link_medium-dark in Pulscen
https://jira.railsc.ru/browse/PC4-28683
> feature(Pulscen): change aui-button_small styles, add aui-link_medium-dark

- package-lock.json
- package.json
После обновления зависимостей версия ломала сборку.
Откат #500, #501, #502
> revert storybook/html update

- src/blocks/blizko/marketing-label/example/marketing_label_example.html
- src/blocks/blizko/marketing-label/marketing-label.css
- src/blocks/blizko/marketing-label/marketing-label_desktop.css
[MINOR]: добавит новые цвета для маркетинговых меток на BLIZKO
https://jira.railsc.ru/browse/BPC-21215
> feat(blizko): add new marketing label colors

- package-lock.json
- src/blocks/common/button/button_transparent-red.css
- src/blocks/common/button/example/transparent_red.html
- src/blocks/common/button/index.js
[MINOR] Добавит прозрачную кнопку с красной рамкой, для удаления товаров.
https://jira.railsc.ru/browse/GOODS-3278
> feature(common): add transparent button with red border

- docs/offered-product-card.css
[PATCH]: исправит отображение узких картинок в сопутствующих товарах в корзине.
https://jira.railsc.ru/browse/BPC-20996
> fix(blizko): fix size img offered products in cart [skip ci]

- src/blocks/blizko/button-order-mobile/button-order-mobile.css
- src/blocks/blizko/button-order-mobile/example/button_order_mobile.html
- src/blocks/blizko/button-order-mobile/index.js
- src/blocks/blizko/marketing-label/example/marketing_label_example.html
- src/blocks/blizko/marketing-label/marketing-label_rating.css
[MINOR]: добавит для мобилы кнопку заказа и модификатор для маркетинговых меток
https://jira.railsc.ru/browse/BPC-21194
> feature(blizko): add mobile order button and modifier marketing label

- package-lock.json
- src/blocks/common/admin-icons/admin-icons__cross.css
- src/blocks/common/admin-icons/example/admin_cross.html
- src/blocks/common/admin-icons/index.js
- src/blocks/common/admin-link/admin-link_normal.css
- src/blocks/common/admin-link/example/link_normal.html
- src/blocks/common/admin-link/index.js
- src/blocks/common/button/button_transparent-red.css
[MINOR] Добавит иконку "крестик" и стиль ссылки "не жирный" для страницы создания товара. https://jira.railsc.ru/browse/GOODS-3248
> feature(common): add cross icon & link style without bold

- src/colors/blizko.json
[MINOR]: изменит цвет amber-d5 на BLIZKO
https://jira.railsc.ru/browse/BPC-21174
> fix(blizko): add new color

- src/blocks/blizko/marketing-label/example/marketing_label_example.html
- src/blocks/blizko/marketing-label/index.js
- src/blocks/blizko/marketing-label/marketing-label_discount.css
- src/blocks/blizko/marketing-label/marketing-label_rating.css
[MINOR]: добавит метку скидки на BLIZKO
https://jira.railsc.ru/browse/BPC-21369
> feature(blizko): add discount label

- src/blocks/blizko/offered-product-card/product-card.css
[PATCH]: исправит отображение узких картинок в сопутствующих товарах в корзине
https://jira.railsc.ru/browse/BPC-20996
> fix(blizko): fix size img offered products in cart 2

- src/blocks/blizko/favorite-button/example/common.html
- src/blocks/blizko/favorite-button/example/mobile.html
- src/blocks/blizko/favorite-button/favorite-button.css
[MINOR]: изменит стили при наведении на кнопку добавить в избранное https://jira.railsc.ru/browse/BPC-21398
> fix(blizko): fix styles on hover

- src/blocks/common/admin-button-radio/admin-button-radio.css
- src/blocks/common/admin-button-radio/example/common.html
[MINOR] добавит стиль disabled для button-radio в админке
https://jira.railsc.ru/browse/GOODS-3248
> feature(common): добавит стиль disabled для button-radio

- src/blocks/common/admin-checkbox/admin-checkbox.css
- src/blocks/common/admin-checkbox/example/common.html
[MINOR] Добавит модификаторы цвета для чекбокса
https://jira.railsc.ru/browse/GOODS-3248
> feature(common): добавит модификаторы цвета для чекбокса

- src/blocks/common/admin-button/admin-button-transparent.css
- src/blocks/common/admin-button/example/common.html
- src/blocks/common/admin-button/index.js
[MINOR] Добавит модификатор прозрачной кнопки.
https://jira.railsc.ru/browse/GOODS-3348
> feature(common): add transparent button

- src/blocks/blizko/offered-product-card/example/common.html
- src/blocks/blizko/offered-product-card/product-card.css
[MINOR]: добавит метку скидки на BLIZKO
> feature(offered product card): add discount label

- src/blocks/blizko/offered-product-card/example/common.html
- src/blocks/common/admin-related-products/admin-related-products.css
[PATCH] отключит ховеры у кнопок сопутствующих товаров в мобильных устройствах
https://jira.railsc.ru/browse/GOODS-3381
> fix(common): отключит hover на мобильных устройствах

- docs/admin-checkbox.css
- src/blocks/common/admin-checkbox/admin-checkbox.css
- src/blocks/common/admin-checkbox/example/common.html
[MINOR]: добавит еще один вариант чекбокс-лэйбла с меньшим отступом
https://jira.railsc.ru/browse/PC4-29420?focusedCommentId=224161&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-224161
> feature(PC): add checkbox label modificator

- src/blocks/blizko/marketing-label/marketing-label_mobile.css
[PATCH]: удалит ограничение по высоте у маркетинговых меток
https://jira.railsc.ru/browse/BPC-21855
> fix(marketing label mobile): remove height limit

- src/blocks/pulscen/app-button/app-button_wide.css
https://jira.railsc.ru/browse/PC4-29841
> feat: delete the mask-box-image style

- src/blocks/common/app-button/app-button.css
https://jira.railsc.ru/browse/PC4-29841
[PATCH]: исправит баг с наложением иконки на ios
Нашли ещё кейсы и задачу расширили
> fix(PC): don't repeat mask-image on IOS

- src/blocks/blizko/button/button_padding.css
- src/blocks/blizko/button/index.js
[MINOR]: добавит модификатор aui-button_padding_small
https://jira.railsc.ru/browse/BPC-22146
> feat(blizko button): add modifier

- src/blocks/blizko/marketing-label/marketing-label_rating.css
[PATCH]: увеличит иконки рейтинга компании в листингах 
https://jira.railsc.ru/browse/BPC-21693
> fix(blizko): resize company raiting on listings

- src/blocks/blizko/button-order-mobile/button-order-mobile.css
- src/blocks/blizko/button-order-mobile/example/button_order_mobile.html
[MINOR]: добавит модификаторы button-order-mobile_background-color_orange и button-order-mobile_text-color_white
https://jira.railsc.ru/browse/BPC-22455
> feat(blizko): add modifier

- src/blocks/common/checkbox/checkbox.css
- src/blocks/common/popup-hint/popup-hint_with-icon.css
https://jira.railsc.ru/browse/PC4-30065
[PATCH]: уберёт повторяющиеся изображение на IOS
> fix(pulscen): remove mask-box-image from checkbox and hint

- src/blocks/blizko/button/button.css
- src/blocks/blizko/button/button_transparent.css
https://jira.railsc.ru/browse/BPC-22413
> feature(blizko): add disabled button style

- src/blocks/common/istorage/istorage.js
[MINOR]: добавит создание куки SameSite для user токена
https://jira.railsc.ru/browse/BPC-22715
> feature(common): add ssoUserToken to same site cookie

- src/blocks/blizko/scroll/scroll.css
https://jira.railsc.ru/browse/BPC-22531
> chore(BLIZKO): change border-radius on scroll

- src/blocks/blizko/button/button.css
- src/blocks/blizko/button/button_mobile.css
- src/blocks/blizko/button/example/example_buttons.html
- src/blocks/blizko/button/index.js
[MINOR]: добавит мобильные кнопки на blizko
https://jira.railsc.ru/browse/BPC-22678
> feature(blizko): add mobile button

- src/blocks/blizko/marketing-label/example/marketing_label_example.html
- src/blocks/blizko/marketing-label/marketing-label_mobile.css
[MINOR]: добавит data атрибут для новых маркетинговых меток
https://jira.railsc.ru/browse/BPC-22695
> feature(blizko): add new design for marketing label

- src/blocks/blizko/button-new/button_new.css
[PATCH]: исправит выравнивание текста в копке
https://jira.railsc.ru/browse/BPC-22701
> fix(blizko): fix align text inside button

- src/blocks/blizko/icon/example/icon.html
- src/blocks/blizko/icon/icon.css
https://jira.railsc.ru/browse/BPC-22698
> fix(blizko): добавит data атрибут для кнопки

- src/blocks/blizko/scroll/example/scroll.html
- src/blocks/blizko/scroll/scroll.css
[PATCH]: добавит горизонтальный скролл
https://jira.railsc.ru/browse/BPC-22694
> feature(blizko): add horizont scroll

- src/blocks/blizko/icon/example/icon.html
- src/blocks/blizko/icon/icon.css
[MINOR]: добавит маленькие иконки
https://jira.railsc.ru/browse/BPC-22699
> feature(blizko): add small icons

- src/blocks/blizko/marketing-label/example/marketing_label_example.html
- src/blocks/blizko/marketing-label/marketing-label.css
- src/blocks/blizko/marketing-label/marketing-label_desktop.css
- src/blocks/blizko/marketing-label/marketing-label_mobile.css
[MINOR]: добавит новые цвета для маркетинговых меток
https://jira.railsc.ru/browse/BPC-22896
> feat(blizko): add new label colors

- src/blocks/blizko/marketing-label/example/marketing_label_example.html
- src/blocks/blizko/marketing-label/marketing-label.css
- src/blocks/blizko/marketing-label/marketing-label_desktop.css
[MINOR]: добавит метку цвета green-d202
https://jira.railsc.ru/browse/BPC-22896
> feat(blizko): add new label color

- src/blocks/blizko/icon/example/icon.html
- src/blocks/blizko/icon/icon.css
- src/blocks/blizko/marketing-label/example/marketing_label_example.html
- src/blocks/blizko/marketing-label/marketing-label_mobile.css
[MINOR]: добавит новые цвета для некоторых иконок
https://jira.railsc.ru/browse/BPC-23019
> feature(blizko): add new icons color

- src/blocks/blizko/button-new/button_size.css
[PATCH]: изменит боковые паддинги у новых кнопок
https://jira.railsc.ru/browse/BPC-23106
> fix(blizko): change padding of new buttons

- src/blocks/common/admin-rubric-select/admin-rubric-select.css
[PATCH]: Поправит ширину у иконки рубрики-ссылки и уменьшит отступ у кнопки выбора ссылки https://jira.railsc.ru/browse/GOODS-3960
> fix(common): Поправит ширину у иконки рубрики-ссылки

- src/blocks/common/admin-rubric-select/admin-rubric-select.css
- src/blocks/common/admin-rubric-select/example/common.html
[PATCH] изменит отступы элементов у рубрикатора
https://jira.railsc.ru/browse/GOODS-3960
> fix(common): изменит отступы элементов у рубрикатора

- src/blocks/blizko/icon/icon.css
[PATCH]: заменим иконки на библиотечные
https://jira.railsc.ru/browse/BPC-23315
> fix(blizko): change product icons

- src/blocks/blizko/icon/icon.css
[MINOR]: добавит иконки очередного размера и снимет ховер в мобиле с иконки избранного товара
https://jira.railsc.ru/browse/BPC-23120
> feature(BLIZKO): add new size for aui-icon

- src/blocks/blizko/slider-product-card/slider_product_card.css
[PATCH]: исправит размеры блока карусели
https://jira.railsc.ru/browse/BPC-23175
> feature(BLIZKO): add new styles to the slider [skip ci]

- src/blocks/blizko/icon/example/icon.html
- src/blocks/blizko/icon/icon.css
[PATCH]: исправит цвета у иконки пакета компании и hover у иконки избранных
https://jira.railsc.ru/browse/BPC-23412
> fix(BLIZKO): fix company rank icon and hover for favorite

- src/blocks/blizko/button-desktop/button_color.css
- src/blocks/blizko/button-desktop/example/index.html
- src/blocks/blizko/icon/icon.css
[MINOR]: добавит новый цвет для кнопки и иконки телефона для десктопа
https://jira.railsc.ru/browse/BPC-23657
> feature(BLIZKO): add new button color and phone icon color for desktop [skip ci]

- src/blocks/blizko/product-short-card/product-short-card.css
https://jira.railsc.ru/browse/BPC-23612
[MINOR]: перенесет стили recent-products, offer-root and discount-products из проекта
> feat(BLIZKO): change style recent products block

- src/blocks/blizko/product-short-card/product-short-card.css
[PATCH]: исправит border radius для картинок
https://jira.railsc.ru/browse/BPC-23797
> fix(BLIZKO): fix border radius for aui-product-short-card__image-container

- src/blocks/blizko/icon/icon.css
- src/blocks/blizko/product-short-card/example/index.html
[MINOR]: добавит иконку размером 12х12
https://jira.railsc.ru/browse/BPC-23712
> feature(BLIZKO): add aui-icon_nano

- src/blocks/blizko/button-mobile/button_clear.css
- src/blocks/blizko/button-mobile/button_color.css
- src/blocks/blizko/button-mobile/button_mobile.css
- src/blocks/blizko/button-mobile/button_size.css
- src/blocks/blizko/button-mobile/example/index.html
- src/blocks/blizko/button-mobile/index.js
[MINOR]: заменит aui-button-new на aui-button-mobile
https://jira.railsc.ru/browse/BPC-23747
> chore(BLIZKO): change name aui-button-new to aui-button-mobile

- src/blocks/blizko/list/list.css
- src/blocks/blizko/list/list_ordinary.css
https://jira.railsc.ru/browse/BPC-23875
[MINOR]: изменит стили второго шага корзины
> feature(BLIZKO): change styles cart step_2

- src/blocks/common/admin-number-input/admin-number-input.css
- src/blocks/common/admin-number-input/example/common.html
- src/blocks/common/admin-text-input/admin-text-input.css
- src/blocks/common/admin-text-input/example/common.html
[MINOR]: Add invalid style to text and number inputs
https://jira.railsc.ru/browse/GOODS-4175
> feature(common): Add invalid style to text and number inputs

- src/blocks/blizko/button-desktop/button_color.css
- src/blocks/blizko/button-desktop/example/index.html
- src/blocks/blizko/icon/icon.css
[MINOR]: add hover styles for desktop buttons
https://jira.railsc.ru/browse/BPC-23507
> feature(BLIZKO): add hover styles for desktop buttons

- src/blocks/blizko/button/button_color.css
https://jira.railsc.ru/browse/BPC-24226
> fix(colors): update value of orange color

- src/blocks/blizko/icon/icon.css
[MINOR]: add white back arrow icon
https://jira.railsc.ru/browse/BPC-23813
> feature(BLIZKO): add white back arrow icon

- src/blocks/blizko/button/button_size.css
[MINOR]: resize desktop button M-size
https://jira.railsc.ru/browse/BPC-24304
> feature(BLIZKO): resize desktop button M-size

- src/blocks/blizko/marketing-label/marketing-label_listing_desktop.css
https://jira.railsc.ru/browse/BPC-24541
> feature(BLIZKO): change the marketing label font-size

- .npmrc
- configs/npm-script.compose.yml
- package-lock.json
- package.json
- src/blocks/pulscen/button/button_disabled.css
- src/blocks/pulscen/button/example/common_disabled.html
- src/blocks/pulscen/button/index.js
- src/blocks/pulscen/cs-button/cs_button_disabled.css
- src/blocks/pulscen/cs-button/example/cs_button_disabled.html
- src/blocks/pulscen/cs-button/index.js
https://jira.railsc.ru/browse/PC4-31944
> feature(button, cs_button): добавит модификатор disabled, зафиксирует версию node.js
